version: '3.8'

services:
  xml-watcher:
    image: xml-watcher:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: 1000:1000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./input/:/input:rw
      - ./output/:/output:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
